version: '3.6'

services:
  typo3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TYPO3_VERSION=11.5
    container_name: typo3
    restart: unless-stopped
    environment:
      - TYPO3_ADMIN_USERNAME=admin
      - TYPO3_ADMIN_PASSWORD=adminadmin
      - TYPO3_DB_HOST=db
      - TYPO3_DB_NAME=typo3
      - TYPO3_DB_USERNAME=typo3
      - TYPO3_DB_PASSWORD=typo3
    volumes:
      - railway-typo3-app:/var/www/html/
    ports:
      - 8144:80
    networks:
      - db

  db:
    image: mariadb:10.11
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=typo3
      - MYSQL_DATABASE=typo3
      - MYSQL_USER=typo3
      - MYSQL_PASSWORD=typo3
      - MYSQL_INITDB_SKIP_TZINFO=yes
      - TZ=Europe/Amsterdam
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    volumes:
      - railway-typo3-db:/var/lib/mysq
    networks:
      - db

networks:
  db:

volumes:
  railway-typo3-app:
  railway-typo3-db:
